### ISSUE TITLE
Does this library support Expo?

### ISSUE THREAD

**Issue by Ripplz** [wxik/react-native-rich-editor#106]
I'm considering implementing this on my Expo react-native project but I can't find any references to Expo on the repo.

Does it support Expo? Has anyone successfully implemented it on an Expo project?

Expo Snack links would be appreciated.

**Comment by ariesbrylle-bms** [comment]
Yep, I have implemented it in Expo.

**Comment by stulip** [comment]
Expo is supported, and I did not put related Examples in the project.
