### ISSUE TITLE
Toolbar buttons activate/deactivate erratically after backspacing

### ISSUE THREAD

**Issue by apgsn** [wxik/react-native-rich-editor#107]
Toolbar buttons for text formatting seem to activate/deactivate in a sketchy way when backspace is used.
This issue can be easily reproduced in the [example page](https://wxik.github.io/react-native-rich-editor/web/) following these steps:
1) type some text
2) press the `bold` button and type some more, the new text is bold
3) press `backspace` until you delete all bold text _and_ some plain text
4) type some text: the text is not bold, but the `bold` button is still active.

At this point you have to press the `bold` button twice (or more) to deactivate it and fix its appearance. This happens on reverse too (same steps as before, but inverting plain and bold text), and for many other actions (set italic, underline, etc.).

**Comment by cibeleasreis** [comment]
Please see if this temp solution works for you: https://github.com/wxik/react-native-rich-editor/issues/101#issuecomment-733780388

**Comment by apgsn** [comment]
@cibeleasreis it didn't work, but thanks anyway.

**Comment by stulip** [comment]
@apgsn What you said should be that the toolbar is displayed abnormally because the format callback is not triggered. I will fix it as soon as possible.

**Comment by stulip** [comment]
[Fixed the subsequent release 1.3.2 version](https://github.com/wxik/react-native-rich-editor/commit/3ebf0814ad65409c8e95d48e1e58c989e0cd242f)

**Comment by apgsn** [comment]
@stulip thank you very much for your help. Can you make these updates available as a npm release? The current version is still 1.3.0.
