### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by apgsn** [wxik/react-native-rich-editor#114]
Is there a way to retrieve the cursor (caret) position? I'd like to have the editor view automatically scroll to the position the cursor is located at.

**Comment by karpov-denys** [comment]
You can try to manage it by yourself.  RichEditor has property` onHeightChange`. `onHeightChange` is only called when the editor is expanded. So you need to add a ScrollView as a wrapper and use `scrollTo ` function

**Comment by karpov-denys** [comment]
Something like that:

`
.....
const [editorHeight, setEditorHeight] = useState(40);
const [scrollViewHeight, setScrollViewHeight] = useState(0);
.....
const refEditor = useRef<RichEditor>();
const refScrollView = useRef<ScrollView>();
.....
.....
<ScrollView
        ref={refScrollView}
        style={{ flex: 1 }}
        contentContainerStyle={{ height: editorHeight }}
        onLayout={(event: LayoutChangeEvent) => {
          const { x, y, height, width } = event.nativeEvent.layout;
          setScrollViewHeight(height);
        }}
      >
        <RichEditor
          ref={refEditor}
          initialFocus={true}
          useContainer={false}
          pasteAsPlainText={true}
          initialContentHTML={value}
          editorInitializedCallback={() => null}
          placeholder={"Add Item"}
          onChange={(value: string) => {
            let text = value;
            if (checkTextLength(value, maxLength)) {
              return;
            }
            if (editorHeight >= scrollViewHeight) {
              refScrollView?.current?.scrollToEnd();
            }
            if (value === "<br>") {
              text = "";
            }
            inputHandler(text);
          }}
          onHeightChange={(height: React.SetStateAction<number>) => {
            setEditorHeight(height);
            if (editorHeight >= scrollViewHeight) {
              setTimeout(() => {
                refScrollView && refScrollView?.current?.scrollToEnd();
              });
            }
          }}
        />
      </ScrollView>
`

**Comment by Andrea-Arguello** [comment]
Did you ever find a solution to this? This would be a nice feature to have. Not necessarily to scroll to the end of the text, but to scroll to the caret position (what if someone is editing text, for that matter).

**Comment by chuyenim** [comment]
In addition, the editor does not automatically collapse shorter when deleting text

**Comment by sanjaykmwt94222** [comment]
Adding style to RichEditor as follows 
`style={{borderBottomWidth: 10, borderColor: 'transparent'}}`

this will also call onHeightChange when deleting text

Although its a hack, right now working for me

**Comment by Andrea-Arguello** [comment]
Check #152

**Comment by Jeyoung-Park** [comment]
try this.
in file './node_modules/react-native-pell-rich-editor/src/editor.js'
change this line
var height = Math.max(docEle.scrollHeight, body.scrollHeight);
to
var height=body.scrollHeight;

and then use onHeightChange to get the editor height and use it when scrolling.

I think is is not a perfect solution but it can help solve this problem to certain extension.

**Comment by stulip** [comment]
`1.8.0` This problem has been resolved

**Comment by ZeeshanAhmadKhalil** [comment]
@stulip  how can we get cursor position, i need cusror position on focus.
+ it's not scrolling automatically we have to handle it manually as mentioned in the docs
