### ISSUE TITLE
How to handle "blur" more robustly?

### ISSUE THREAD

**Issue by SnidelyWhiplash** [wxik/react-native-rich-editor#118]
I was wondering how I can get the editor so simply blur when clicking anywhere outside the WebView. Currently I can't blur it except by programmatically calling `this.editor.blurContentEditor()`

Also, is there any way to respond to the blur event? I tried an `onBlur` prop but it doesn't seem like that exists.

Basically I have a form with several fields, only one of which is a RichEditor. I want to show & hide my RichToolbar based on which field is selected (I have it stickied to the top of the keyboard).

Thanks!

**Comment by stulip** [comment]
[1.5.1](https://github.com/wxik/react-native-rich-editor/releases/tag/v1.5.1)

**Comment by SnidelyWhiplash** [comment]
Thanks, will try it out. I think my first issue had more to do with the `keyboardShouldPersistTaps` value on my parent ScrollView, so this should solve my issues.

Appreciate the quick action!
