### ISSUE TITLE
Editor Height and load speed of this editor.

### ISSUE THREAD

**Issue by Anna-0629** [wxik/react-native-rich-editor#122]
Hello, developers!
I am building post app using this module, and cannot control style of this editor. Of course I have checked all issue reports and solutions, but I did not find exactly fit my case.
My problem is height of text editor. If I enter lots of contents, loading time is too slow when the contents I have entered flow over the height of textarea. I mean after the content overflows, then the height is resized in about 3~4 seconds. This is really serious problem for me. I am sorry if I report silly "issue". but need help... Thanks. Anna.

**Comment by Andrea-Arguello** [comment]
Hi! Did you find a solution to the slow load?

**Comment by Jamal-ReachFirst** [comment]
Reopen this

**Comment by hssdiv** [comment]
for height use initialHeight={100}
