### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by cristianoccazinsp** [wxik/react-native-rich-editor#124]
Looks like events do not go through the WebView on Android. This means text cannot be selected nor the webview interacted with. Works fine on iOS.

I have tried a scroll view, and it still doesn't work. Thoughts?

**Comment by cristianoccazinsp** [comment]
Closing as this was related to my own code bugs and very odd behaviour within react native's event system. It seems like it is working fine within a regular view and using `scrollEnabled={true}` on the webview/RichEditor component.

**Comment by Andrea-Arguello** [comment]
Could you provide a sample of what your code looks like? I am experiencing the same issue on Android, but text occasionally being selected at random and other times not.

**Comment by cristianoccazinsp** [comment]
For me it was related to having Touchables and FlatList/ScrollViews wrapping the component.  After removing all touchables and just using Views the issue went away. 

I'm not using any special code or anything that I could share and be useful. It's basically a few <Views> and the component.

Also, I'm using `useContainer={false}` and `scrollEnabled={false}` now.  The component still behaves oddly when inside a FlatList (e.g., scroll bars not visible, or the webview not scrolling at all without using the text knob). Because of this, I opted out to use "full screen" version that opens in a <Modal>.

**Comment by Andrea-Arguello** [comment]
Thanks! I had put it inside a TouchableWithoutFeedback because the component was not blurring as expected, never crossed my mind that it would be because of that.
For me, scrollEnabled was not working, and I needed a styled container. I fixed this by nesting the editor inside a scrollview, which itself was nested in a view with the styles.

**Comment by stulip** [comment]
`1.8.0` This problem has been resolved

**Comment by Meqr1** [comment]
hello everyone really need help right now....

```ts
import { useEffect, useRef } from 'react'
import {
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Text,
  TouchableNativeFeedback,
  TouchableWithoutFeedback,
  View,
} from 'react-native'
import { RichEditor, RichToolbar, actions } from 'react-native-pell-rich-editor'

export const NoteEditor = () => {
  const richText = useRef()

  return (
    <View>
      <ScrollView>
        <KeyboardAvoidingView>
          <RichEditor
            ref={richText}
            placeholder="..."
            androidHardwareAccelerationDisabled
            style={{ height: screenX }}
            useContainer={false}
          />
        </KeyboardAvoidingView>
      </ScrollView>
      <RichToolbar
        editor={richText}
        actions={[
          actions.setBold,
          actions.setItalic,
          actions.setUnderline,
          actions.heading1,
          actions.undo,
          actions.redo,
          actions.insertImage,
        ]}
      />
    </View>
  )
}
```

**Comment by MostafaHamdy3** [comment]
@Meqr1 
Any solution for the scrolling and keyboard dismiss?

**Comment by Meqr1** [comment]
@MostafaHamdy3 i dont think i have to solution that you need.

but the problem with my [app](https://nuranote.web.app) was that above the Main View for the Scroll View i was looking for a swipe event which override the Main View events.

i dont think i have the correct answer sorry.

**Comment by MostafaHamdy3** [comment]
@Meqr1 
Thanks for your answer, I found a solution for scrolling and ignor the keyboard 😂
