### ISSUE TITLE
onHeightChange never decreases

### ISSUE THREAD

**Issue by cristianoccazinsp** [wxik/react-native-rich-editor#125]
`onHeightChange` never decreases.  In fact, fully re-rendering the component will trigger a previously stored height, even if it is rendered with `key={random}`

**Comment by Afeixiaohuozi** [comment]
Did you have  solved the problem

**Comment by sonminguyen** [comment]
It still happen to me! Did you have any solutions ?

**Comment by Jeyoung-Park** [comment]
try this.
in file './node_modules/react-native-pell-rich-editor/src/editor.js'
change this line
`var height = Math.max(docEle.scrollHeight, body.scrollHeight);`
to
`var height=body.scrollHeight;`

I think is is not a perfect solution but it can help solve this problem to certain extension.

**Comment by stulip** [comment]
`1.8.2` Fixed height, cursor view positioning issues
