### ISSUE TITLE
Mentions feature

### ISSUE THREAD

**Issue by dngconsulting** [wxik/react-native-rich-editor#130]
Hello, 

Do you know if there is any "mention/@" feature in react native rich editor ? I have to display a list when the user types '@', is this kind of behaviour easy to implement by listening to a onChangeText callback for example.

Thanks.

**Comment by stulip** [comment]
Can monitor `onKeyDown` or `onKeyUp` 

`
handleKeyDown = data => {
        console.log('KeyDown:', data);
    };
`
`data = {"key": "@", "keyCode": 50}`
