### ISSUE TITLE
How to Implement Custom Action for Text Color, background Color, and Text Alignment

### ISSUE THREAD

**Issue by anupamvijayvergia** [wxik/react-native-rich-editor#135]
How can I implement these custom actions? Possible to call execCommand from the component?

**Comment by stulip** [comment]
see [1.6.3](https://github.com/wxik/react-native-rich-editor/releases/tag/v1.6.3)
need use command function

**Comment by anupamvijayvergia** [comment]
Thank you @stulip I updated to 1.6.4 and was able to achieve this. However, I have noticed after the update if I select a text it gets unselected immediately especially if there's just one word in the editor. Any idea how can this be fixed? 

This is log coming in the terminal every time I select something. Ideally, editorInitializedCallback should be called once right? 

```
Toolbar click, selected items (insert end callback): ["justifyLeft"]
```


```
// this function will be called when the editor has been initialized
  function editorInitializedCallback() {
    RichText.current?.registerToolbar(function(items) {
      // items contain all the actions that are currently active
      console.log(
        'Toolbar click, selected items (insert end callback):',
        items,
      );
    });
  }
```

**Comment by stulip** [comment]
`registerToolbar ` It is registered to monitor the toolbar, and the console output is normal

**Comment by FloMueh** [comment]
hi @anupamvijayvergia 

can you tell me how do you managed to add a button for text color? 

i just need to map the functionality of the "bold" Button to another. Just replace the <b> with <div style="color: red">. 
I tried to create a custom action but i can not manage to insert the div between the selected text.

**Comment by stulip** [comment]
`1.8.0` add `foreColor` & `hiliteColor`
