### ISSUE TITLE
RichTextEditor collapsing on Android

### ISSUE THREAD

**Issue by jessypouliot98** [wxik/react-native-rich-editor#145]
**Description:**
It looks like when editor loses focus it collapses to 0px height. This happens by pressing the Hardware back button on android. It also sometimes happens when I press focus an other input and then remove focus from that input.

This doesnt affect iOS.

**dependancies:**
react: 17.0.1 (same for 16.13.1)
react-native: 0.63.4
react-native-pell-rich-editor: 1.5.5 (same for 1.3.0) (latest 1.6.x version crashes my app when trying to load an image that does'nt exist)
react-native-webview: 9.0.2 (tried latest and errors with onMessage something)
react-native-navigation: 6.12.2 (editor is inside a modal from this package)

**Steps to reproduce:**

1. Open a modal
2. focus editor
3. press Device back button

**Additional information:**
This problem appeared after upgrading our app from react-native 0.61 to 0.63.

Component has nothing really complicated
```
<RichTextEditor
    ref={r => (this.richtext = r)}
    style={[t.mL1, t.flex1, t.h16, t.pT50]}
    initialContentHTML={this.initialContent}
/>
```

![Screenshot_20210115_170933_com huawei himovie overseas](https://user-images.githubusercontent.com/35693647/104783734-af9b6c00-5754-11eb-8214-c6c3a20f08dd.jpg)
![Screenshot_20210115_170936_com huawei himovie overseas](https://user-images.githubusercontent.com/35693647/104783738-b0340280-5754-11eb-937d-f6bd3e8cf236.jpg)

**Comment by jessypouliot98** [comment]
Update: This also does the same thing with react-native-pell-rich-text-editor@1.6.4 (it doesnt crash anymore for some reason) and still happens with react-native-webview 10.10.4 (11.X.X isnt supported as postMessage is deprecated)

**Comment by jessypouliot98** [comment]
Update: This is unrelated to this package.

**Comment by Bilal-Abdeen** [comment]
This seems to be a problem with react-native-webview. I used the following to fix it. 

```
<RichEditor 
  .... 
  androidLayerType="software"
/>
```

**Comment by dhruvpvx** [comment]
> > This seems to be a problem with react-native-webview. I used the following to fix it.
> > ```
> > <RichEditor 
> >   .... 
> >   androidLayerType="software"
> > />
> > ```
> 
> still problem occurs in android

I this this is because very long strings in between html tags

**Comment by sandipshiwakoti** [comment]
Using  androidLayerType="software" is a bad approach because it slows down the performance of the editor.
