### ISSUE TITLE
embed youtube video url to upload the video

### ISSUE THREAD

**Issue by wikramdas** [wxik/react-native-rich-editor#147]
Hello team,
I am having issue regarding uploading a video embed url so that a video will be play when user see the post so is it possible to upload the video embed url. I read the complete documentation and also read all the issue but I am unable to find any solution. If you support the embed url so kindly let me know.
Thanks

**Comment by stulip** [comment]
You can use the embedded HTMl code provided by YouTube and use the editor's `insertHTML` to embed 

`<div>`
`<iframe width="100%" height="200"  src="https://www.youtube.com/embed/6FrNXgXlCGA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
`</div>`
