### ISSUE TITLE
How to change cursor/selection color

### ISSUE THREAD

**Issue by Andrea-Arguello** [wxik/react-native-rich-editor#148]
React Native's TextInput has a selectionColor prop, which also defines the cursor's color. How can we implement this in the rich editor?

**Comment by Andrea-Arguello** [comment]
On src/editor.js, I made the following changes
```diff
- body { overflow-y: hidden; -webkit-overflow-scrolling: touch;height: 100%;background-color: ${backgroundColor};}
+ body { caret-color: ${color}; overflow-y: hidden; -webkit-overflow-scrolling: touch;height: 100%;background-color: ${backgroundColor};}
```
I wanted the caret to be the same color as my text, but you are welcome to change as needed. This could be a nice option to have.

**Comment by stulip** [comment]
Thank you very much, this attribute has been added in `1.8.0 `
