### ISSUE TITLE
can not delete image

### ISSUE THREAD

**Issue by Afeixiaohuozi** [wxik/react-native-rich-editor#149]
When I insert a picture in the middle of a paragraph of text，It is difficult for me to delete the photo again, unless all the text behind it is deleted。
Moreover, when inserting a picture on an IOS device, the cursor will always move to the front of the entire text。

Can anyone solve this problem?

**Comment by UADACID** [comment]
I have the same problem, is there a solution?

**Comment by Afeixiaohuozi** [comment]
> I have the same problem, is there a solution?

update Latest v1.7.0 ,this problem  has been solved
