### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by disko998** [wxik/react-native-rich-editor#156]
Hi guys,

My force rtl but for some reason rich editor text is ltr still, so I'm wondering does this package support rtl?

**Comment by stulip** [comment]
I am not familiar with RTL [reference ](https://github.com/wxik/react-native-rich-editor/issues/167)

**Comment by disko998** [comment]
Right to left, so my app forces RTL mode but the text was still on the LTR. Anyways it can be fixed by setting `direction: rtl;` to contentCSSText.

**Comment by saurabh874** [comment]
@disko998  i am also facing same issue even i tried your solution put direction:rtl to contentCSSText
editorStyle={{
                                    contentCSSText: { direction: I18nManager.isRTL ? 'rtl' : 'ltr' },
                                    cssText: { textAlign: I18nManager.isRTL ? 'right' : 'left' },
                                    backgroundColor: theme.colors.primaryBg,
                                    fontSize: 14,
                                    color: theme.colors.text,
                                    fontFamily: theme.fonts.regular.fontFamily }}

**Comment by SoundousBahri** [comment]
Could you please explain your soltion better
where to put `rirection:rtl;`

**Comment by SherazAlii001** [comment]
i Also need RTL Support  have you find any solution @disko998

**Comment by Nippon007** [comment]
@SherazAlii001  did you find any solution to this ??
