### ISSUE TITLE
Can't set border radius for RichEditor

### ISSUE THREAD

**Issue by mikykonst** [wxik/react-native-rich-editor#158]
I set borderRadius in styles. But they don't applied in Android.

`<View style={styles.editorContainer}>
        <RichEditor
          style={styles.editor}
          useContainer={true}
          editorStyle={contentStyle}
          // @ts-ignore
          ref={richText}
          initialContentHTML={
            isScope ? item.name : (item as TaskModel).description
          }
          placeholder="Enter name"
          onChange={handleEditorTextChange}
        />
        {
          <RichToolbar
            style={styles.toolBar}
            editor={richText}
            actions={[actions.setBold, actions.setItalic]}
          />
        }
      </View>`

`editor: {
    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
    minWidth: '100%',
    minHeight: 300,
  },
  toolBar: {
    borderBottomRightRadius: 24,
    borderBottomLeftRadius: 24,
    backgroundColor: styleVariables.colors.white,
  },`

![image](https://user-images.githubusercontent.com/17960435/112511017-aead3900-8d9a-11eb-81ea-a85d3a039dcd.png)

**Comment by truyenle16398** [comment]
Any solution?

**Comment by stulip** [comment]
@mikykonst @truyenle16398 

You can add the property `containerStyle={{borderRadius: 24}}` to RichEditor.
Test version `"react-native-webview": "11.4.4"`

**Comment by truyenle16398** [comment]
> @mikykonst @truyenle16398
> 
> You can add the property `containerStyle={{borderRadius: 24}}` to RichEditor.
> Test version `"react-native-webview": "11.4.4"`

It not work for me

My editor
`<RichEditor
                ref={richRef}
                placeholder={I18n.t("groups.type_message")}
                editorStyle={editorStyle}
                onChange={(value: string) => setMessage(value)}
                useContainer={false}
                initialHeight={verticalScale(50)}
                onFocus={() => onFocusInput()}
                style={styles.rich}
                initialFocus={false}
                containerStyle={{ borderRadius: 15 }}
            />`
My version `"react-native-webview": "11.4.4","react-native-pell-rich-editor": "^1.7.0"`

**Comment by truyenle16398** [comment]
> @mikykonst @truyenle16398
> 
> You can add the property `containerStyle={{borderRadius: 24}}` to RichEditor.
> Test version `"react-native-webview": "11.4.4"`

Thank U very much <3
