### ISSUE TITLE
Android - focusContentEditor not working correctly

### ISSUE THREAD

**Issue by nfjones87** [wxik/react-native-rich-editor#159]
Hi there. 

Very simple implementation: 

`
import React, { Component }  from 'react';
import { View } from 'react-native';
import {RichEditor} from 'react-native-pell-rich-editor'

class editorTest extends Component {

  componentDidMount(){
    this.richtext.focusContentEditor()
  }

  render(){
    return (
      <View style={{flex: 1}}>
         <RichEditor
            ref={(r) => this.richtext = r}
            initialContentHTML={'Hello World '}
          /> 
     </View>
    )
  }
}
`

It just very quickly opens then closes the keyboard. 

I have looked into the source code to see how it works.
It works by (if on android), creating an invisible textInput to make the keyboard show up, then switches focus to the WebView. Unfortunately, upon switching to the WebView, the keyboard drops back down.

"react-native-pell-rich-editor": "^1.7.0"
"react-native": "0.61.2"
"react-native-webview": "^11.3.2"

Anyone else experiencing this?

**Comment by trugdn** [comment]
any solution ?

**Comment by stulip** [comment]
@nfjones87 @trugdn 

Do not use this method in componentDidMount, use the following method instead 
```
<RichEditor  initialFocus={true} />

```

`focusContentEditor` is effective when tested in the Android emulator
