### ISSUE TITLE
Can't edit the height of the input

### ISSUE THREAD

**Issue by yasir-netlinks** [wxik/react-native-rich-editor#16]
I am trying to edit the height, but it doesn't change at
I tried this 
```
<RichEditor
              ref={rf => (this.richText = rf)}
              initialContentHTML={values.about}
              style={{
                minHeight: 50,  // this doesn't work
                height: 50 // this also doesn't work

              }}
            />
```

**Comment by jasongaare** [comment]
add `flex: 0` to the style along side the height you want

**Comment by kapilgpt06** [comment]
this is also not working

**Comment by stulip** [comment]
The height will automatically change according to the height of the content (useContainer = true), you can set false to use a custom view wrapper.
