### ISSUE TITLE
while writting code and press New line it breaks and create new div

### ISSUE THREAD

**Issue by Nilesh8451** [wxik/react-native-rich-editor#172]
![16206544211948354410172590621311](https://user-images.githubusercontent.com/50334886/117669256-51433f00-b1c4-11eb-8db9-bb66bc77acbf.jpg)
I want to write the code like this. Can anyone help me how can I achieved that please?

![16206549257725552287311946479765](https://user-images.githubusercontent.com/50334886/117670428-7e442180-b1c5-11eb-9125-8cbb01235c29.jpg)
When I tried this is happening with default code option behaviour

**Comment by RashVenkat6795** [comment]
@Nilesh8451 any solution on this issue ?

**Comment by stulip** [comment]
![2021-06-03 10 14 36](https://user-images.githubusercontent.com/5770971/120576049-b81ae780-c454-11eb-8155-82ee868f7728.gif)

@RashVenkat6795 @Nilesh8451 `1.8.5` It has been fixed

**Comment by sadikyalcin** [comment]
@stulip I think it should be removed from content too not just code view.

 https://github.com/wxik/react-native-rich-editor/issues/146

**Comment by caturadjiprasetyo** [comment]
i use 1.9.0 it still create new <div> when click enter
