### ISSUE TITLE
How to clean value in editor?

### ISSUE THREAD

**Issue by truyenle16398** [wxik/react-native-rich-editor#174]
Hi everyone,
I want to clean value (all text) when click button send.
Any solution?
![simulator_screenshot_08A88FAB-A1C1-46B0-BF63-543794EF7EFA](https://user-images.githubusercontent.com/55780534/118282854-eb72f200-b4f8-11eb-80cd-641c415330fa.png)

**Comment by anhzaikutebs** [comment]
u cant try use ref:
ex: richTextRef.current.setContentHTML('');

**Comment by truyenle16398** [comment]
> u cant try use ref:
> ex: richTextRef.current.setContentHTML('');

Thank U

**Comment by truyenle16398** [comment]
> u cant try use ref:
> ex: richTextRef.current.setContentHTML('');

Can you help me how to set border radius for editor. I used borderRadius in styles but it do not work in android

**Comment by louicoder** [comment]
> u cant try use ref: ex: richTextRef.current.setContentHTML('');

This worked for me! Thanks alot :)
