### ISSUE TITLE
Module not found Can't resolve '../img/blockquote.png' 

### ISSUE THREAD

**Issue by bilalsha** [wxik/react-native-rich-editor#175]
I am getting this error while trying to build react-native app. I tried on mac, linux, and windows. All are getting this issue.

`D:/arazy-mobile/node_modules/react-native-pell-rich-editor/src/RichToolbar.js
Module not found: Can't resolve '../img/blockquote.png' in 'D:\arazy-mobile\node_modules\react-native-pell-rich-editor\src'`

**Comment by stulip** [comment]
After updating to `1.8.2` to see if this problem still exists
