### ISSUE TITLE
IOS Japanese keyboard

### ISSUE THREAD

**Issue by adamodigital** [wxik/react-native-rich-editor#178]
Hi there.

I'm using your library and have some issues with the Japanese keyboard. The editor always keeps the first character.
For example, typing "ta" should give you "た", but instead gives you "tた."

![34F112C4-F626-4C8E-B5B1-489C358D4C96](https://user-images.githubusercontent.com/36678260/119921857-f28a0d80-bf98-11eb-8eeb-ec270955048e.jpg)

Can you help me?
Thank you so much

**Comment by stulip** [comment]
![image](https://user-images.githubusercontent.com/5770971/119925091-54517400-bfa7-11eb-9e0e-6f9df98178a2.png)


There is no such situation on my side as you said

**Comment by adamodigital** [comment]
Thank you for your response.
I using version 1.6.4
Did you the latest version?

**Comment by stulip** [comment]
`1.8.3` May have resolved this issue

**Comment by adamodigital** [comment]
Thank you, let's me try it.

**Comment by stulip** [comment]
`1.8.3` Published
