### ISSUE TITLE
onCursorPosition not work

### ISSUE THREAD

**Issue by rdtf1230** [wxik/react-native-rich-editor#183]
onCursorPosition={(scrollY) => console.log("yY", scrollY)}

when i press enter, thats not work XD

can i ask the solution??

**Comment by stulip** [comment]
`useContainer = false` failed

**Comment by rdtf1230** [comment]
> `useContainer = false` failed

here is my code
![image](https://user-images.githubusercontent.com/58766003/121284439-d0d54280-c917-11eb-8ccc-dd93ca636faf.png)

what i should do??

**Comment by stulip** [comment]
Is it version 1.8.5? 
There is no problem with this code in the examples

**Comment by rdtf1230** [comment]
> Is it version 1.8.5?
> There is no problem with this code in the examples

![image](https://user-images.githubusercontent.com/58766003/121287475-91f5bb80-c91c-11eb-867c-43d7824e5f9a.png)
using 1.8.5
hmm.......

**Comment by rdtf1230** [comment]
I don't know how it works.
When the library code in node_module was replaced with edit mode, it started working normally.

**Comment by stulip** [comment]
Clean the `metro` cache, delete `node_module` and try reinstalling

**Comment by rdtf1230** [comment]
> Clean the `metro` cache, delete `node_module` and try reinstalling

I guess that is correct,
Thank you for spending time for me.
have a nice day!!
