### ISSUE TITLE
Not able to scroll in android

### ISSUE THREAD

**Issue by ArchanaUshaVijayan** [wxik/react-native-rich-editor#189]
While entering multiple line scroll is coming in the left side. But when try to scroll using touch not able to scroll. Any one got same issue

**Comment by ArchanaUshaVijayan** [comment]
solved

**Comment by hanzoow** [comment]
How ? pleases show us

**Comment by Karansidds** [comment]
Hey @ArchanaUshaVijayan, can you please share the solution?
