### ISSUE TITLE
How to scroll to end when enter new line?

### ISSUE THREAD

**Issue by whitesnow9291** [wxik/react-native-rich-editor#19]
user should scroll manually to type at the end.
Can it scroll automatically new line added?

**Comment by xuho** [comment]
I need this feature as well, did you has solution @whitesnow9291?

**Comment by stulip** [comment]
There is no good solution at present, prepare to study and realize the plan in the near future

**Comment by marlti7** [comment]
I need this feature as well, did you has solution @whitesnow9291?

**Comment by whitesnow9291** [comment]
@marlti7 ,@xuhu, sorry, I didn't find any solution yet. just using as it is :(

**Comment by stulip** [comment]
`1.8.0`
