### ISSUE TITLE
setContentHTML doesnot update the height of the editor

### ISSUE THREAD

**Issue by bittu1028** [wxik/react-native-rich-editor#192]

**Comment by harishgupta01** [comment]
@bittu1028 Did you also face an issue where the cursor position remains at the start of the text (instead of at the end) if calling setContentHTML?

**Comment by bittu1028** [comment]
yes @harishgupta01  i fix that using range and selection

**Comment by harishgupta01** [comment]
Thanks @bittu1028 . Is it possible for you to help me out with the changes needed to fix this for android? I do have the fix for the web but struggling to get it done for Android.

**Comment by bittu1028** [comment]
do you know how to set curser on web ?

**Comment by bittu1028** [comment]
@stulip I have created a pr for this issue. please take a look !!!

**Comment by harishgupta01** [comment]
@bittu1028 I was actually asking for the changes done to fix the cursor issue where the cursor appears at the start of the text after calling setContentHTML. So, basically, I want the cursor to appear at the end of the text. As you mentioned that can be fixed using range and selection. So, I do have a fix for the web but it uses documents. I was just wondering how that can be fixed for the android clients.

**Comment by bittu1028** [comment]
@harishgupta01  can you create a question on StackOverflow rather than this thread?

**Comment by harishgupta01** [comment]
I got it resolved as I was using setContentHTML instead of insertHTML. Thanks for the help!
