### ISSUE TITLE
Not able to change the cursor position to the end of text after calling setContentHTML on android

### ISSUE THREAD

**Issue by harishgupta01** [wxik/react-native-rich-editor#194]
By default, the cursor appears at the start when setting a string using setContentHTML. I want to cursor to be there at the end of the text but am not able to do so for the android app.  I think the same can achieve using the below API for the web though:const range = document.createRange();
let selection = document.getSelection();

Looking for something similar for android. Tried as below:

inputRef = React.createRef<TextInput>();
this.inputRef.current!.selection={start:5,end:5}

But didn't work. Please help me out. Thanks!

**Comment by christophemenager** [comment]
I have the same issue, how did you handle this ? :)

**Comment by Robiullah2244** [comment]
I have the same issue, how did you handle this?

**Comment by harishgupta01** [comment]
@christophemenager @Robiullah2244 Did you try `insertText` API ?

**Comment by Robiullah2244** [comment]
> @christophemenager @Robiullah2244 Did you try `insertText` API ?

No. How can I use it? Can you please give an example here? 

Thanks for your time and consideration

**Comment by Robiullah2244** [comment]
I have to use it to add character limitations of input text.
I came out with a solution. My solution is 


`handleChange = (val) => {
        if(val != this.prevDescVal){
            let rawVal = val;
            if(val.replace(/<[^>]*>/g, '').length > 1500 ){
                this.richtext.current?.setContentHTML('');
                this.richtext.current?.insertHTML(this.prevDescVal);
                this.toast.show({
                    text: "Maximum limit 1500",
                    type: 'failed',
                });
            }else{
                this.prevDescVal = rawVal;
            }
        }
    }`

**Comment by stulip** [comment]
@harishgupta01 
`this.richText.current.setContentHTML(initHTML);`
`this.richText.current.focusContentEditor();`

The above method can be tested, the input focus is at the end of the document

**Comment by Sotatek-AnhNguyen36** [comment]
for anyone looking for the answer, ```setContentHTML``` always places the cursor at the start of the input. 
kinda hacky but this works for me:


```this.richText.current.setContentHTML('')```
`setRichTextContent('something)`

and then:

```
useEffect(() => { 
  if (richTextContent)  setTimeout(() => this.richText.current.insertHTML(richTextContent), 100)
}
,[richTextContent])
```
