### ISSUE TITLE
get offsetX onCursorPosition

### ISSUE THREAD

**Issue by brunokiafuka** [wxik/react-native-rich-editor#195]
Is it possible to get also get the `offsetX` when we getting the cursor position? - or an object that allows us to manage the cursor selection similar to `window.getSelection()` on the web?

Currently, we have on the implementation of the `getSelection` when `createHTML` would be good if can expose the selection object to the native side in case we want also to do a manipulation of the cursor or at least know its position.

> I believe that this would be more a feature request than an actual issue.

**Comment by martinriviere** [comment]
Hi, did you manage getting this `offsetX` cursor position?

**Comment by brunokiafuka** [comment]
> Hi, did you manage getting this `offsetX` cursor position? I would be very interested in such a solution!

Hi @martinriviere, I've ended up doing a custom implementation of the content editable using the [`<WebView/>`](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md) component. 

There I've created a custom HTML that has some functions that would allow me to call the actions to [manipulate the content-editable on my HTML via JS](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascript).

**Comment by martinriviere** [comment]
Thanks for your prompt reply.
I'm currently trying to do same thing keeping this library, using `command`method and `onMessage` prop. If I can't make it work as expected, I'll probably need to implement my own contenteditable in WebView as you did.
