### ISSUE TITLE
Unable to scroll the content inside the editor if the editor is in focus

### ISSUE THREAD

**Issue by shameersn** [wxik/react-native-rich-editor#198]
I use following versions of react and react-native

react: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
**react-native-pell-rich-editor: "^1.8.5"**

Scroll works perfectly if the editor is not in focus and the keyboard is not present.

While trying to edit content inside the editor, lets say list of items, then we can't scroll the content.
The scrolling kind of stuck. Is there any configuration i am missing in the code.
If we dismiss the keyboard and try scrolling, it will work.
The issue is in both iOS and Android, in real devices and simulators.

Please help.

Thank you

**Code**
```javascript
 <ScrollView
          style={[styles.scroll]}
          ref={that.scrollRef}
          scrollEventThrottle={20}>
          <RichEditor
            disabled={disabled}
            editorStyle={contentStyle} // default light style
            ref={that.richText}
            style={styles.rich}
            useContainer={true}
            placeholder={'please input content'}
            initialContentHTML={content}
            editorInitializedCallback={that.editorInitializedCallback}
            onChange={that.handleChange}
            onFocus={that.handleFocus}
            onBlur={that.handleBlur}
            onCursorPosition={that.handleCursorPosition}
            pasteAsPlainText={true}
          />
  </ScrollView>
```

**Comment by stulip** [comment]
Can you run the example project to see if it is normal

**Comment by shameersn** [comment]
Sure will do thanks

**Comment by stulip** [comment]
I happened to be dealing with some bugs mentioned in Issues of this project today, and I am usually very busy without time.

**Comment by shameersn** [comment]
@stulip The example works perfectly. I will compare my code with example.
I am using the entire UI components including the editor and its wrapping scrollview inside another scroll view.
May be that is causing the issue. I will try and debug. 
Thank you for the support.

**Comment by shameersn** [comment]
Following solution fixed my problem : https://github.com/wxik/react-native-rich-editor/issues/152#issuecomment-812913429
