### ISSUE TITLE
insertLink doesn't insert

### ISSUE THREAD

**Issue by sadikyalcin** [wxik/react-native-rich-editor#199]
The `insertLink()` isn't working. Followed the example but it doesn't update the `<RichEditor />` value.

`"react-native": "0.64.2"`
`"react-native-pell-rich-editor": "^1.8.5",`

```
this.textEditor = React.createRef();

this.textEditor.current.insertLink(title, url)

<RichEditor
  ref={this.textEditor}
  placeholder={'Add body...'}
  initialContentHTML={''}
  onChange={body => {
    this.setBody(body);
  }}
/>

```

**Comment by tmbradley** [comment]
Was there any fix to this, besides just closing? I am running into this issue with version ```1.9.0``` when the RichEditor has no value.
