### ISSUE TITLE
Crash app when navigation to screen on Android 

### ISSUE THREAD

**Issue by nghuuton** [wxik/react-native-rich-editor#202]
When i navigation screen from Flatlist to screen has RichEditor will crash app on Android.

I use  
          "react-native": "0.64.1",
           "react-native-pell-rich-editor": "^1.8.6"       
           "react-native-webview": "^11.13.0",

**Comment by christophemenager** [comment]
Crash is due to webview, use androidHardwareAccelerationDisabled to avoid it

**Comment by nghuuton** [comment]
> Crash is due to webview, use androidHardwareAccelerationDisabled to avoid it

Nice, tks u. it's work for me.
