### ISSUE TITLE
Displaying differently in RichTextEditor and rendered HTML View

### ISSUE THREAD

**Issue by KrisLau** [wxik/react-native-rich-editor#205]
In the editor:
![image](https://user-images.githubusercontent.com/46275463/136099868-45ccb245-1a7f-4e85-9fa4-0d38d8c2b622.png)

After being rendered by `HtmlView`:
![image](https://user-images.githubusercontent.com/46275463/136099998-ec290cbf-0895-46a2-aad4-b2bc8f8f6a88.png)

How do I get the `HtmlView` to match the Rich Editor view? Or should I just display it using the Rich Editor to get the most consistent result?

**Comment by KrisLau** [comment]
I ended up using the `RichEditor` as the displaying component which also has the added benefit of not needing another package

**Comment by Overdash** [comment]
Hi, how did you do this? 
I'm trying to also render the RichEditor as a view in a card - would be nice to not have to manually use another HtmlView

**Comment by KrisLau** [comment]
After the user presses save, I take text from the `RichEditor` that the user is typing in and display it into a disabled `RichEditor`
