### ISSUE TITLE
Editor Disappears after height of 800px

### ISSUE THREAD

**Issue by accompso-ltd** [wxik/react-native-rich-editor#235]
Every time I reach a height of 800 px or more the webview stops working however I am still able to type and edit in the editor?

I am working on android 
Version: 1.8.8

````
 return (
    <View style={styles.container}>
                  <ScrollView
                  usecontainer = {true}
                keyboardDismissMode={'none'}
                ref={scrollRef}
                
                nestedScrollEnabled={true}
                scrollEventThrottle={20}>
               
          <RichEditor
         //   androidHardwareAccelerationDisabled={true}
            disabled={false}
            containerStyle={styles.editor}
            ref={RichText}
            style={styles.rich}
            placeholder={"Start Writing Here"}
            initialContentHTML={props.route.params.template.html}
            onChange={(text) => handleChange(text)}
            editorInitializedCallback={editorInitializedCallback}
            onHeightChange={handleHeightChange}
            oncursorPosition={handleCursorPosition}            
            useContainer={true}
          />
      </ScrollView>
      <RichToolbar
        style={[styles.richBar]}
        editor={RichText}
        disabled={false}
        selectedIconTint={"pink"}
        onPressAddImage={onPressAddImage}
        
        insertEmoji={handleEmoji}
        actions={[
          "Save",
          "addData",
          "AddImage",
          actions.setParagraph,
          actions.heading1,
          actions.heading2,
          actions.heading3,
          actions.heading4,
          actions.heading5,
          actions.alignLeft,
          actions.alignCenter,
          actions.alignRight,
          actions.alignFull,
          actions.blockquote,
          "PageHeader",
          "PageFooter",
          actions.line,
          actions.fontSize,
         // 'insertEmoji',
          actions.setBold,
          actions.setItalic,
          actions.insertBulletsList,
          actions.insertOrderedList,
          actions.insertLink,
          actions.setSubscript,
          actions.setSuperscript,
          actions.removeFormat,
          actions.table,
          actions.outdent,
          actions.indent,
          actions.keyboard,
          actions.setStrikethrough,
          actions.setUnderline,
          actions.removeFormat,
          actions.checkboxList,
          actions.undo,
          actions.redo,
          "code2",
          "Delete",
        ]}
        // map icons for self made actions
        iconMap={{
          [actions.setParagraph]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>p</Text>
          ),
          [actions.heading1]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H1</Text>
          ),
          [actions.heading2]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H2</Text>
          ),
          [actions.heading3]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H3</Text>
          ),
          [actions.heading4]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H4</Text>
          ),
          [actions.heading5]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H5</Text>
          ),
          ["addData"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="plus-box"
              size={25}
              color={tintColor}
            />
          ),
          ["PageHeader"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="page-layout-header"
              size={25}
              color={tintColor}
            />
          ),
          ["PageFooter"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="page-layout-footer"
              size={25}
              color={tintColor}
            />
          ),

          ["insertVideo"]: video,

          ["code2"]: ({ tintColor }) => (
            <MaterialComminityIcons name="xml" size={25} color={tintColor} />
          ),
          ["AddImage"]: ({ tintColor }) => (
            <MaterialComminityIcons name="image" size={25} color={tintColor} />
          ),
          ["Save"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="content-save"
              size={25}
              color={tintColor}
            />
          ),
          ["Delete"]: ({ tintColor }) => (
            <MaterialComminityIcons name="delete" size={25} color={tintColor} />
          ),
          insertEmoji: phizIcon,
        }}
        Delete={DeleteModalHandle}
        insertVideo={insertVideo}
        AddImage={selectImageModal}
        table={createTable}
        addData={addData}
        code2={viewRawHtml}
        PageHeader={addPageHeader}
        PageFooter={addPageFooter}
        Save={updateReportDetails}
      />
      <Modal
        animationType="slide"
        transparent={true}
        // onBackdropPress={}
        visible={modal}
        onRequestClose={() => {
          setModal(!modal);
        }}
      >
        <View key={rows + cols} style={styles.modalContainer}>
          {modalInner == "table" && (
            <TableModal
              dataValues={props.route.params}
              insertTable={insertTable}
            />
          )}
          {modalInner == "Data" && (
            <DataModal
              dataValues={props.route.params}
              addData={addHtml}
              type={props.route.params.type}
            />
          )}

          {modalInner == "updateReportDetails" && (
            <UpdateReport
              report={props.route.params.template}
              Save={Save}
              SaveAndExit={SaveAndExit}
            />
          )}
          {modalInner == "RawHtml" && (
            <RawHtml data={article} addData={updateRaw} />
          )}
          {modalInner == "SelectImage" && (
            <SelectImage
              dataValues={props.route.params}
              addImage={insertImage}
            />
          )}
          {modalInner == "DeleteModal" && <DeleteModal Delete={Delete} />}
        </View>
      </Modal>
  
 
    </View>
  );
};

export default ReportCreatorV2;

const styles = StyleSheet.create({
  /********************************/
  /* styles for html tags */
  a: {
    fontWeight: "bold",
  },
  div: {
    fontFamily: "monospace",
  },
  p: {
    fontSize: 30,
  },
  /*******************************/
  container: {
    opacity: 1,
    flex: 1,
    backgroundColor: "#F5FCFF",
  },
  editor: {
    backgroundColor: "white",
    opacity: 1,
    borderColor: "black",
    borderWidth: 1,
  },
  rich: {
    opacity: 1,
    minHeight: 300,
  },
  richBar: {
    height: 50,
    backgroundColor: "#F5FCFF",
  },
  text: {
    fontWeight: "bold",
    fontSize: 20,
  },
  tib: {
    textAlign: "center",
    color: "#515156",
  },
  modalContainer: {
    flex: 2,
    padding: 10,
    backgroundColor: "#c0cdd1",
    alignContent: "center",
    alignSelf: "center",
    width: Dimensions.get("window").width / 1.2,
    borderColor: "black",
    margin: 100,

    borderRadius: 15,
  },
});

````

**Comment by accompso-ltd** [comment]
should have read the docs better

`  let handleCursorPosition = useCallback((scrollY) => {
    // Positioning scroll bar
    scrollRef.current.scrollTo({y: scrollY - 30, animated: true});
}, [])

  return (
    <View style={styles.container}>
                  <ScrollView
                  usecontainer = {true}
                keyboardDismissMode={'none'}
                ref={scrollRef}
                
                nestedScrollEnabled={true}
                scrollEventThrottle={20}>
               
          <RichEditor
         //   androidHardwareAccelerationDisabled={true}
            disabled={false}
            containerStyle={styles.editor}
            ref={RichText}
            style={styles.rich}
            placeholder={"Start Writing Here"}
            initialContentHTML={props.route.params.template.html}
            onChange={(text) => handleChange(text)}
            editorInitializedCallback={editorInitializedCallback}
            onHeightChange={handleHeightChange}
            oncursorPosition={handleCursorPosition}            
            useContainer={true}
          />
      </ScrollView>
      <RichToolbar
        style={[styles.richBar]}
        editor={RichText}
        disabled={false}
        selectedIconTint={"pink"}
        onPressAddImage={onPressAddImage}
        
        insertEmoji={handleEmoji}
        actions={[
          "Save",
          "addData",
          "AddImage",
          actions.setParagraph,
          actions.heading1,
          actions.heading2,
          actions.heading3,
          actions.heading4,
          actions.heading5,
          actions.alignLeft,
          actions.alignCenter,
          actions.alignRight,
          actions.alignFull,
          actions.blockquote,
          "PageHeader",
          "PageFooter",
          actions.line,
          actions.fontSize,
         // 'insertEmoji',
          actions.setBold,
          actions.setItalic,
          actions.insertBulletsList,
          actions.insertOrderedList,
          actions.insertLink,
          actions.setSubscript,
          actions.setSuperscript,
          actions.removeFormat,
          actions.table,
          actions.outdent,
          actions.indent,
          actions.keyboard,
          actions.setStrikethrough,
          actions.setUnderline,
          actions.removeFormat,
          actions.checkboxList,
          actions.undo,
          actions.redo,
          "code2",
          "Delete",
        ]}
        // map icons for self made actions
        iconMap={{
          [actions.setParagraph]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>p</Text>
          ),
          [actions.heading1]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H1</Text>
          ),
          [actions.heading2]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H2</Text>
          ),
          [actions.heading3]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H3</Text>
          ),
          [actions.heading4]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H4</Text>
          ),
          [actions.heading5]: ({ tintColor }) => (
            <Text style={[styles.tib, { color: tintColor }]}>H5</Text>
          ),
          ["addData"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="plus-box"
              size={25}
              color={tintColor}
            />
          ),
          ["PageHeader"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="page-layout-header"
              size={25}
              color={tintColor}
            />
          ),
          ["PageFooter"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="page-layout-footer"
              size={25}
              color={tintColor}
            />
          ),

          ["insertVideo"]: video,

          ["code2"]: ({ tintColor }) => (
            <MaterialComminityIcons name="xml" size={25} color={tintColor} />
          ),
          ["AddImage"]: ({ tintColor }) => (
            <MaterialComminityIcons name="image" size={25} color={tintColor} />
          ),
          ["Save"]: ({ tintColor }) => (
            <MaterialComminityIcons
              name="content-save"
              size={25}
              color={tintColor}
            />
          ),
          ["Delete"]: ({ tintColor }) => (
            <MaterialComminityIcons name="delete" size={25} color={tintColor} />
          ),
          insertEmoji: phizIcon,
        }}
        Delete={DeleteModalHandle}
        insertVideo={insertVideo}
        AddImage={selectImageModal}
        table={createTable}
        addData={addData}
        code2={viewRawHtml}
        PageHeader={addPageHeader}
        PageFooter={addPageFooter}
        Save={updateReportDetails}
      />
      <Modal
        animationType="slide"
        transparent={true}
        // onBackdropPress={}
        visible={modal}
        onRequestClose={() => {
          setModal(!modal);
        }}
      >
        <View key={rows + cols} style={styles.modalContainer}>
          {modalInner == "table" && (
            <TableModal
              dataValues={props.route.params}
              insertTable={insertTable}
            />
          )}
          {modalInner == "Data" && (
            <DataModal
              dataValues={props.route.params}
              addData={addHtml}
              type={props.route.params.type}
            />
          )}

          {modalInner == "updateReportDetails" && (
            <UpdateReport
              report={props.route.params.template}
              Save={Save}
              SaveAndExit={SaveAndExit}
            />
          )}
          {modalInner == "RawHtml" && (
            <RawHtml data={article} addData={updateRaw} />
          )}
          {modalInner == "SelectImage" && (
            <SelectImage
              dataValues={props.route.params}
              addImage={insertImage}
            />
          )}
          {modalInner == "DeleteModal" && <DeleteModal Delete={Delete} />}
        </View>
      </Modal>
  
 
    </View>
  );
};

export default ReportCreatorV2;

const styles = StyleSheet.create({
  /********************************/
  /* styles for html tags */
  a: {
    fontWeight: "bold",
  },
  div: {
    fontFamily: "monospace",
  },
  p: {
    fontSize: 30,
  },
  /*******************************/
  container: {
    opacity: 1,
    flex: 1,
    backgroundColor: "#F5FCFF",
  },
  editor: {
    backgroundColor: "white",
    opacity: 1,
    borderColor: "black",
    borderWidth: 1,
  },
  rich: {
    opacity: 1,
    minHeight: 300,
  },
  richBar: {
    height: 50,
    backgroundColor: "#F5FCFF",
  },
  text: {
    fontWeight: "bold",
    fontSize: 20,
  },
  tib: {
    textAlign: "center",
    color: "#515156",
  },
  modalContainer: {
    flex: 2,
    padding: 10,
    backgroundColor: "#c0cdd1",
    alignContent: "center",
    alignSelf: "center",
    width: Dimensions.get("window").width / 1.2,
    borderColor: "black",
    margin: 100,

    borderRadius: 15,
  },
});
`

**Comment by jakehasler** [comment]
@accompso-ltd I'm having this issue too but I'm unclear on what your solution was based on your code samples. Do you remember what specifically you changed to get this working?

**Comment by aviaryan77** [comment]
```
 <RichEditor
        ...         
        useContainer={false}
      />
```

**Comment by doougui** [comment]
> @accompso-ltd I'm having this issue too but I'm unclear on what your solution was based on your code samples. Do you remember what specifically you changed to get this working?

Did you manage to solve this? I'm having the same problem here :(
Setting useContainer to false only hides my entire Editor

**Comment by doougui** [comment]
I managed to solve this with `useContainer={false}`, but that alone wouldn't solve the problem.

So, for anyone interested, I ended up doing this:

```js
        <RichEditorWrapper style={{ height: editorHeight }} hasError={hasError} disabled={disabled}>
          <RichEditor
            ref={richText}
            placeholder={placeholder ?? 'Digite...'}
            useContainer={false}
            onHeightChange={(e) => {
              setEditorHeight(e);
            }}
            style={{
              borderWidth: stringToNumber(theme.borders.widths.thin),
              borderTopLeftRadius: stringToNumber(theme.borders.radius.medium),
              borderTopRightRadius: stringToNumber(theme.borders.radius.medium),
              borderColor: getBorderColor(),
            }}
            editorStyle={{
              placeholderColor: theme.colors.quaternary[100],
              backgroundColor: disabled
                ? theme.colors.quaternary[15]
                : theme.colors.singletons.white,
            }}
            disabled={disabled}
            {...props}
            onChange={handleChange}
            androidLayerType="software"
          />
        </RichEditorWrapper>
```

with `editorHeight` being a state

```js
const [editorHeight, setEditorHeight] = React.useState<number>(200);
```

**Comment by hoanghuy0604** [comment]
if you have this problem because of Navigation, just add `animationEnabled:false` to options param
`<Stack.Screen
        name="Main"
        component={MainNavigator}
        options={{
          animationEnabled: false,
        }}
      />`

**Comment by daydayhappychao** [comment]
just remove `androidLayerType="software"`.
I debug this all day
