### ISSUE TITLE
RichToolbar is hided by keyboard when textinput focusing 

### ISSUE THREAD

**Issue by july-12** [wxik/react-native-rich-editor#26]
react-native info:
![image](https://user-images.githubusercontent.com/920487/72330110-e7f70d00-36f0-11ea-80da-cd1abfc14123.png)

problem like blew:
![image](https://user-images.githubusercontent.com/920487/72329954-a8c8bc00-36f0-11ea-9913-d83974a0f7b8.png)

**Comment by serhanozcan** [comment]
You will try change the `keyboardVerticalOffset`.
Like this;
`<KeyboardAvoidingView behavior={'position'} enabled keyboardVerticalOffset={140}>`
This is **not** the complete solution just example, but you can change it according to your own design.

**Comment by ambessh** [comment]
<KeyboardAvoidingView>your UI</KeyBoardAvoidingView>
your UI should be styled accordingly to  be able to be effected by KeyboardAvoidingView

**Comment by stulip** [comment]
You can refer to [example](https://github.com/wxik/react-native-rich-editor/blob/master/examples/src/example.js)

**Comment by ambessh** [comment]
add tab bar from react navigation 5 and it worked for me. you can still
hide the tab bar at that editor page and it still works.
