### ISSUE TITLE
Keyboard open automatically

### ISSUE THREAD

**Issue by PedramGhdi** [wxik/react-native-rich-editor#263]
Hi guys,
I have a problem that when I open the page or screen which RichEditor is over there, my keyboard open automatically and focus to typing.

How can I stop it?

**Comment by prabir-vora** [comment]
You can go to src/editor.js inside the node_modules for the package and comment out autofocus=true. That's what I did to prevent autofocus.

**Comment by PedramGhdi** [comment]
Hi @prabir-vora ,
Unfortunately, there is no autofocus overthere...

**Comment by PedramGhdi** [comment]
Oh, I found it and changed it to false.
content.autofocus = false;

it was very down in **var init** variable.
Thank you so much
