### ISSUE TITLE
insertImage sizing problem

### ISSUE THREAD

**Issue by sangmin-iam** [wxik/react-native-rich-editor#279]
I am trying to solve this problem for a while. but I can't find a solution. I need help!
like the picture below, when I insert an image it doesn't show the full image. 

I have tried manually to set width and height on the image, it works but I want to keep the original size of the image automatically.

is there any work around instead of setting manually?

<img width="273" alt="Screen Shot 2022-10-06 at 2 38 57 PM" src="https://user-images.githubusercontent.com/69471244/195474371-a910113e-7bdd-4857-8842-2f53bb63943f.png">

**Comment by zsomborgellerfi** [comment]
@sangmin-iam Have you managed to solve this? We are having the same issue

**Comment by Siwoo4u** [comment]
I have same issue
my solution..

const your_image_original_width = // original image size
const your_image_original_height = // original image size


const width = Dimensions.get('window').width
const imageWidthPercent = (width/your_image_original_width)*100
const imageHeight = your_image_original_height * imageWidthPercent/100

richText.current.insertImage(filepath,`width:${width}px; height:${imageHeight.toFixed(0)}px;`)
