### ISSUE TITLE
How to show Scrollbar in Editor

### ISSUE THREAD

**Issue by SyedHaris94** [wxik/react-native-rich-editor#29]
How can i show the vertical scroll in editor when the content is large

**Comment by vinivitin** [comment]
You can wrap editor into `ScrollView`.

```
<ScrollView>
  <RichEditor
    ref={richText}
  />
</ScrollView>
```

**Comment by ShumGG** [comment]
@vinivitin when I do it, the editor dissapears

**Comment by ealmiladi** [comment]
> @vinivitin when I do it, the editor dissapears

`useContainer={false}`

**Comment by stulip** [comment]
`1.8.0`

**Comment by willrcline** [comment]
I have the opposite question. I want to get rid of the scrollbar that is present in the richTextEditor

**Comment by brunnolou** [comment]
> I have the opposite question. I want to get rid of the scrollbar that is present in the richTextEditor

I solved this by NOT setting a border! I left unstyled and the scroll inside the `<RichEditor>` was gone
