### ISSUE TITLE
Long text paste shows EMPTY editor  [ANDROID]

### ISSUE THREAD

**Issue by jerinwega** [wxik/react-native-rich-editor#292]
with pasteAsPlainText={true} / pasteAsPlainText={false}

tried to copy and paste / copy as plain text and paste in ANDROID

the editor shows empty (was able to save ) but while viewing again the editor shows the same behaviour.

 <KeyboardAvoidingView 
                  enabled={showToolbar}
                  flex={1}
                  behavior={Platform.OS === ANDROID ? "height" : "padding" }
                  keyboardVerticalOffset={scaledHeight(120)}
                >
                    <ScrollView 
                    flex={1} 
                    ref={scrollRef}
                    contentContainerStyle={{ flexGrow: 1 }}
                    nestedScrollEnabled
                    keyboardShouldPersistTaps="always" 
                    >
                    <RichEditor
                      onFocus={() => setShowToolbar(true)}
                        androidLayerType="software"
                        accessibilityRole={'none'}
                        accessibilityLabel={"Description Field"}
                        accessibilityHint={"Add Description"}
                        showsVerticalScrollIndicator={false}
                        editorStyle={{
                            caretColor: colorMode === 'light' ? 'black': 'white',
                            backgroundColor: colorMode === 'light' ? 'white' : 'black' , 
                            color: colorMode ==='light' ? DARK_COLOR : LIGHT_COLOR,
                            placeholderColor: colorMode === 'light' ? '#a3a3a3' : '#525252',
                            initialCSSText: `${customRichDocumentFont}`,
                            contentCSSText:`
                                padding: 14px; 
                                font-family: 'Lato';
                                font-size: ${scaledFont(20)}px !important;
                                `,
                        }}

                        style={{flex: 1, borderRadius: 20, opacity: 1 }}
                        ref={richText}
                        placeholder={"ideas"}
                        pasteAsPlainText={true}
                        initialFocus={false}
                        useContainer={true}
                        onCursorPosition={handleCursorPosition}
                        containerStyle={{
                            borderRadius: 20, 
                            borderBottomLeftRadius: 0,
                            borderBottomRightRadius: 0,
                            borderBottomWidth: 0,
                            backgroundColor: colorMode === 'light' ? 'white' : 'black', 
                            borderWidth: 1,
                            borderColor: colorMode === 'light' ? '#d4d4d4' : '#404040',
                            }}
                        initialContentHTML={description}
                        onChange={(text) => handleChange(text, 'description')}
                    />
                </ScrollView>
                <RichToolbar
                    editor={richText}
                    disabled={!showToolbar}
                    disabledIconTint ={colorMode === 'light' ? '#a3a3a3' : '#525252'}
                    selectedIconTint={colorMode === 'light' ? '#cb7bff' : '#c05eff'}
                    iconTint={colorMode=== 'light' ? DARK_COLOR : LIGHT_COLOR }
                    iconSize={scaledFont(22)}
                    flatContainerStyle={{ paddingHorizontal: 6 }}
                    actions={[
                    actions.setBold,
                    actions.setUnderline,
                    actions.setStrikethrough,
                    actions.insertBulletsList,
                    actions.insertOrderedList,
                    actions.alignLeft,
                    actions.alignCenter,
                    actions.alignRight,
                    ]}
                    style={[
                        styles.richTextToolbarStyle, { 
                        height: scaledHeight(48), 
                        backgroundColor: colorMode=== 'light' ? LIGHT_COLOR : DARK_COLOR, 
                        borderColor: colorMode==='light' ? '#d4d4d4' : '#404040'}
                    ]}
                />
                </KeyboardAvoidingView>

**Comment by jerinwega** [comment]
almost above 60 lines of text paste seems to have this issue

**Comment by pratheekgv19** [comment]
@jerinwega did you find any solution for this?
