### ISSUE TITLE
Editor Scroll is not working.

### ISSUE THREAD

**Issue by harleenarora** [wxik/react-native-rich-editor#30]
Hi, 

User should scroll manually to type at the end. But scroll is not working.

**Comment by philsam** [comment]
You can change it in this line `/node_modules/react-native-pell-rich-editor/src/RichEditor.js`
`set renderWebView = () => (
        <WebView
            useWebKit={true}
            scrollEnabled={true} />`

scrollEnabled should be set to true

**Comment by astulip** [comment]
Pass in `scrollEnabled` to override properties
`<RichEditor ref={that.richText} initialContentHTML={initHTML}  scrollEnabled={false}/>`

By default, you need to use the `ScrollView` package for processing, you can refer to the example project

**Comment by ishiestar** [comment]
@stulip I ran the example project. However, wrapping the RichEditor in a ScrollView doesn't work since the editor disappears altogether. No amount of height or flex is enough to show the editor, even in your example project. What am I missing?

**Comment by stulip** [comment]
@ishiestar 
The editor disappears? The example automatically becomes higher according to the content height.

**Comment by ishiestar** [comment]
Well, it can't be seen on the screen if I keep the scroll view. If I remove it and give a minHeight to the editor, only then I can see it.

**Comment by stulip** [comment]
see `1.8.0`

**Comment by Hel5ing** [comment]
> @stulip I ran the example project. However, wrapping the RichEditor in a ScrollView doesn't work since the editor disappears altogether. No amount of height or flex is enough to show the editor, even in your example project. What am I missing?

same problem

**Comment by stulip** [comment]
@Hel5ing Does the examples in the master have the same problem?

**Comment by Hel5ing** [comment]
> @Hel5ing Does the examples in the master have the same problem?

@stulip 
thanks for your quick response, and  I have figured it out just now;
there is something wrong with ther Metro, maybe the cache problem, and after I restart it, the editor works perfect. 
Sorry for borthering you,  it's a great package! 🌼
