### ISSUE TITLE
WebView is focused and keyboard is shown automatically on iOS

### ISSUE THREAD

**Issue by kjparkdavid** [wxik/react-native-rich-editor#304]
When opening a screen with `<RichEditor />`, the keyboard is shown and the WebView is focused automatically on iOS, but not on Android.

I have tried adding `initialFocus={false}` with the same result.
Is there a way to not automatically focus on the editor on iOS?

**Comment by manosKas** [comment]
trying to solve this too

**Comment by stulip** [comment]
Fixed 'initialFocus={false}' not taking effect
please update `1.8.9`

**Comment by Letty** [comment]
There is one thing with the default properties now. You set the initialFocus in RichEditor.js to `false` and in editor.js to `true`. Which is a conflict. Isn't it better to set the prop in RichEditor.js to `true` and just pass it to editor.js?

**Comment by stulip** [comment]
@Letty Thank you very much.I haven't maintained it for a year, and Example has been upgraded to the latest RN version in a hurry.I ignored some problems when changing this problem
