### ISSUE TITLE
How to add Keyboard.dismiss on IOS 

### ISSUE THREAD

**Issue by harleenarora** [wxik/react-native-rich-editor#31]

**Comment by Dev4ster** [comment]
hello my friend, also this problem and managed to solve - calling the **blurContentEditor** function

example:

`editorRef.blurContentEditor();`

I hope I was helpfull :)

**Comment by stulip** [comment]
functions `dismissKeyboard`

**Comment by thunderclap1030** [comment]
This is function for manual dismiss keyboard but i don't know how to make "Done" button above the keyboard :D

`   textEditor.current.dismissKeyboard()
`

**Comment by saravanakumargn** [comment]
I used `KeyboardAccessoryView` to manage my Toolbar and Done button. 
[https://wix.github.io/react-native-ui-lib/docs/KeyboardAccessoryView/](https://wix.github.io/react-native-ui-lib/docs/KeyboardAccessoryView/)
