### ISSUE TITLE
[WITH SOLUTION] Exception in HostFunction: TypeError: expected dynamic type 'array', but had type 'string'

### ISSUE THREAD

**Issue by timlukastlt** [wxik/react-native-rich-editor#372]
This error occurs with the latest WebView version. For example, I encountered it with version 13.12.2 and Expo SDK 52.0.5.

To resolve this issue:
1. Navigate to `node_modules -> react-native-pell-rich-editor -> RichEditor.js`.
2. On line 270, change `dataDetectorTypes={'none'}` to `dataDetectorTypes={["none"]}`.

Please fix this!

**Comment by globemediaofficial** [comment]
I also had this issue (specifically on Android) with Expo SDK 52 and your solution worked for me. Thanks!

**Comment by stulip** [comment]
I will pay attention to and fix this issue recently

**Comment by timlukastlt** [comment]
https://github.com/wxik/react-native-rich-editor/pull/373

**Comment by feri-irawan** [comment]
Same issue with ` "react-native-pell-rich-editor": "^1.9.0"`, when we can install the new version?

**Comment by spacester7563** [comment]
Go to \node_modules\react-native-pell-rich-editor\src\RichEditor.js
And at line 270 change dataDetectorTypes={'none'} to dataDetectorTypes={['none']}
as shown in image 
![image](https://github.com/user-attachments/assets/e4aacb5a-37ac-4348-9667-78391d5ba9ba)
