### ISSUE TITLE
Several Issues Must Be Fixed!

### ISSUE THREAD

**Issue by michelazzam** [wxik/react-native-rich-editor#42]
I was search for a Rich Text Editor, and thought that i finally found one..

But after installing, i found so many issues in it which took of my time to fix, more time than actually building it..

Some of what i found: 
- RENAME YOUR IMAGES PATH!  
          if you renamed your image (@2x, @3x ..) at least rename their path!

- RUN BEFORE YOU COMMIT!
          A simple error occurred in index.js that says something about exporting.. and after checking it apparently you can't export without giving it a naming, but after i exported each alone it did the work..

But honestly after reaching this point. Please give it more focus.. it can be useful!

Have a good day.

**Comment by stulip** [comment]
> I still don't understand what you said
