### ISSUE TITLE
Height is fixed , can't be change when adding large content

### ISSUE THREAD

**Issue by kapilgpt06** [wxik/react-native-rich-editor#46]

**Comment by ambessh** [comment]
go to RichEditor.js it has some code already in comments. understand that and that will work ,editor will auto size according to the virtual keyboard.
go to editor.js in css on the top and change postion of .content to fixed.

**Comment by wxik** [comment]
v1.0.7 Support copy editor.js modification, and pass it into RichEditor as props html

**Comment by stulip** [comment]
The height will automatically change according to the height of the content (useContainer = true)

**Comment by quanghungit** [comment]
> The height will automatically change according to the height of the content (useContainer = true)

When I delete the content, the height doesn't shrink
any solution?

**Comment by stulip** [comment]
@quanghungit 

There is currently this problem

**Comment by ambessh** [comment]
RichEditor.js has some code which is commented. understand that code and
tweak it .it will wok.

**Comment by ariesbrylle-bms** [comment]
you can try this.

put your editor inside a scroll view with fixed height, then every time you put content on the editor, update the height of the editor but you can scroll since you have a scroll view.

`<ScrollView style={{ height: 400 }} keyboardDismissMode={"none"}>
              <RichEditor
                ref={richText}
                useContainer={false}
                containerStyle={{ minHeight: height }}
                editorStyle={{
                  width: "99%",
                  borderWidth: 1,
                  backgroundColor: "white",
                  borderColor: CONSTANTS.PRIMARY_COLOR,
                }}
                initialContentHTML={initHTML}
                editorInitializedCallback={editorInitializedCallback}
                onHeightChange={(e) => {
                  console.log("change height");
                  console.log(e);
                  setHeight(e);
                }}
              />
   </ScrollView>`

`const [height, setHeight] = useState(400);`

**Comment by jaynguyen89** [comment]
> > The height will automatically change according to the height of the content (useContainer = true)
> 
> When I delete the content, the height doesn't shrink
> any solution�?

@quanghungit
I found a solution for your problem as I also need the editor to shrink when content is reduced.

In the package folder, open RichEditor.js, then in `onMessage(event`, case `messages.CONTENT_CHANGE`, add the following line before break:

if (data.length < 150) this.setWebHeight(Dimensions.get('window').height * 0.25);
                             |                                                                                              |
                             |-----------Can set to any value of your specific need--------|

**Comment by stulip** [comment]
`1.8.0`
