### ISSUE TITLE
TypeError: editor.registerToolbar is not a function

### ISSUE THREAD

**Issue by minhtet-BeeComTech** [wxik/react-native-rich-editor#50]
import React, { useEffect, useState, useCallback, useContext, createRef } from 'react'
import { Button, KeyboardAvoidingView, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { RichEditor, RichToolbar } from 'react-native-pell-rich-editor';

const initHTML = `<br/>
<center><b>Pell.js Rich Editor</b></center>
<center>React Native</center>
<br/>
</br></br>
`;

const Example = props => {
    const richText = createRef();

    const save = async () => {
        // Get the data here and call the interface to save the data
        let html = await richText.current?.getContentHtml();

        console.log('html', html)
        // console.log(html);
        alert(html);
    }

    const onPressAddImage = () => {
        // insert URL
        richText.current?.insertImage(
            'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1024px-React-icon.svg.png',
        );
        // insert base64
        // richText.current?.insertImage(`data:${image.mime};base64,${image.data}`);
        richText.current?.blurContentEditor();
    }

    const onHome = () => {
        props.navigation.push('index');
    }

    return (
        <SafeAreaView style={styles.container}>
            <View style={styles.nav}>
                <Button title={'HOME'} onPress={onHome} />
                <Button title="Save" onPress={save} />
            </View>
            <ScrollView >
                <View>
                    <View style={styles.item}>
                        <Text>To: </Text>
                        <TextInput style={styles.input} placeholder={'stulip@126.com'} />
                    </View>
                    <View style={styles.item}>
                        <Text>Subject: </Text>
                        <TextInput style={styles.input} placeholder='Rich Editor Bug 😀' />
                    </View>
                </View>
                <RichEditor ref={richText} initialContentHTML={initHTML} style={styles.rich} />
            </ScrollView>
            <RichToolbar
                style={styles.richBar}
                editor={richText}
                iconTint={'#000033'}
                selectedIconTint={'#2095F2'}
                selectedButtonStyle={{ backgroundColor: 'transparent' }}
                onPressAddImage={onPressAddImage}
                getEditor={() => richText}
            />
        </SafeAreaView>
    )
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5FCFF',
    },
    nav: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: 5,
    },
    rich: {
        minHeight: 300,
        flex: 1,
    },
    richBar: {
        height: 50,
        backgroundColor: '#F5FCFF',
    },
    scroll: {
        backgroundColor: '#ffffff',
    },
    item: {
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderColor: '#eee',
        flexDirection: 'row',
        height: 40,
        alignItems: 'center',
        paddingHorizontal: 15
    },

    input: {
        flex: 1
    }
});

export { Example } @astulip

**Comment by wxik** [comment]
hooks please use useRef instead of createRef

[https://github.com/stulip/react-native-pell-rich-editor/commit/c18853157427b7d497fa9757988e707b718b0930](https://github.com/stulip/react-native-pell-rich-editor/commit/c18853157427b7d497fa9757988e707b718b0930)
