### ISSUE TITLE
App crashes at runtime[Android]

### ISSUE THREAD

**Issue by kuldeepworkid** [wxik/react-native-rich-editor#52]
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.meadow9, PID: 25469
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.rnscreens.ScreenContainer.isTransitioning()' on a null object reference

Above is the error when is try to launch the app

**Comment by wxik** [comment]
At present, it is found that the crash problem may be caused by a certain version of react-native-webview, you can update to the latest version and try

**Comment by AntonioErdeljac** [comment]
I had a crash happen on Android, don't know if this can help anyone, but my problems went away after I wrapped it in `<ScrollView>`. Found out that someone else fixed a similar problem on Android by wrapping it as well #124 

```
 <ScrollView>
        <RichEditor
            placeholder={placeholder}
            disabled={disabled}
            initialHeight={100}
            onFocus={handleFocus}
            onBlur={handleBlur}
            editorStyle={isFocused ? styles.editorFocused : styles.editor}
            initialContentHTML={value}
            onChange={onChangeText}
        />
</ScrollView>
```

**Comment by Timus23** [comment]
> I had a crash happen on Android, don't know if this can help anyone, but my problems went away after I wrapped it in `<ScrollView>`. Found out that someone else fixed a similar problem on Android by wrapping it as well #124
> 
> ```
>  <ScrollView>
>         <RichEditor
>             placeholder={placeholder}
>             disabled={disabled}
>             initialHeight={100}
>             onFocus={handleFocus}
>             onBlur={handleBlur}
>             editorStyle={isFocused ? styles.editorFocused : styles.editor}
>             initialContentHTML={value}
>             onChange={onChangeText}
>         />
> </ScrollView>
> ```

Same happened to me and i wrapped it with scroll view and it is working fine now. but didn't knw the exact cause why it happened without scrollview.

**Comment by vitorguima** [comment]
coming from the future to thank u lol @AntonioErdeljac

**Comment by MujeebAyokunle** [comment]
I've done everything above but it's still crashing the application. I wrapped it in a ScrollView, Added several recommended props but it's still not resolved. My react native version is 0.76..3, react-native-pell-rich-editor version is 1.9.0, and react-native-webview is 13.13.2. Someone should please help @AntonioErdeljac  @stulip
