### ISSUE TITLE
Can not scroll RichEditor after setting useContainer to false

### ISSUE THREAD

**Issue by prathasaxena** [wxik/react-native-rich-editor#64]
<View style={[ {height: 300/825*height}]}>
                <ScrollView  ref={that.scrollRef} style={[styles.scroll, themeBg]} keyboardDismissMode={'none'}>
                    <RichEditor
                        // initialFocus={true}
                        editorStyle={contentStyle} // default light style
                        containerStyle={{paddingBottom:10/825*height, height:300/825*height}}
                        ref={that.richText}
                        style={[styles.rich, themeBg]}
                        placeholder={''}
                        useContainer={false}
                        editorInitializedCallback={that.editorInitializedCallback}
                        onChange={that.handleChange}
                        onHeightChange={that.handleHeightChange}
                    />

                </ScrollView>
                </View>

this is the code i am trying to work with,  where style scroll is 
    scroll: {
        flex:1,
        backgroundColor: 'green',
        height: 300/825*height
        // marginTop:10/825*height,
        // paddingBottom:20/825*height
    },
    rich: {
        minHeight: 300/825*height,
        flex: 1,
    },
but i'm not able to scroll through the RichEditor

**Comment by Dev4ster** [comment]
hello my friend, by default the editor is encapsulated in a webview and for that reason it is kind of complex to configure the height, I managed to solve involving rich text with a container and controlling its height through the onHeightChange function.

see this example

```
<RichInputContainer style={{height: editorHeight}}>
                    <RichEditor
                    scrollEnabled
                    ref={EditorRef}
                    placeholder="Type here"
                    useContainer={false}
                    onHeightChange={(e)=> {
                      console.log('change height')
                      console.log(e)
                      setEditorHeight(e)
                    }}
                    />
</RichInputContainer>
```
`const [editorHeight, setEditorHeight ] = useState();`

and then you control the height through a state, it’s great to make the editor 'expandable', and I believe it solves your problem.

**Comment by Florian-Bolli** [comment]
Hi there,
I tried your method, but onHeightChange is only called when the editor is expanded. I can not shrink its size like this, do you have a solution?

**Comment by stulip** [comment]
`1.8.0`
