### ISSUE TITLE
format content when pasting

### ISSUE THREAD

**Issue by Dev4ster** [wxik/react-native-rich-editor#66]
Hello, I would like to know how I do when the text is pasted. and didn't come with external html, but only the text

I saw that there is an action called **removeFormat**, I want to know how I trigger it when some content is pasted in the editor

**Comment by Dev4ster** [comment]
hello my friends, being able to solve the process was a bit complicated, but I managed to get him to remove all the html from the copied content.

to do this it is necessary to enter the source code of the plugin and access the file
**node_modules / react-native-pell-rich-editor / src / editor.js**

it is necessary to add an EventListener, to monitor the events of the content that is our clipboardData area.

approximately on line 250 you will find the list of events, add one more:

```
addEventListener(content, 'paste', function (e) {
                e.stopPropagation();
                e.preventDefault();
                content = e.clipboardData.getData('text/plain');
                document.execCommand('insertText', false, content); // can survive through exec
});
```

for me this works because I will not accept all types of html within the richtext, just bold, italics and underline.

Hope this helps ;)

**Comment by chungmktg** [comment]
thank you so much :))
