### ISSUE TITLE
Android short press editor doesn't pop up keyboard

### ISSUE THREAD

**Issue by dejavu20180307** [wxik/react-native-rich-editor#67]
On IOS, it works fine, click any editor area will put cursor to top and pop up keyboard.
But on Android, click lower part of editor area will not pop up keyboard, user can only press first line of editor to start input.

**Comment by MortadhaFadhlaoui** [comment]
Any update about fixing thit issue

**Comment by SRSMurthy** [comment]
> On IOS, it works fine, click any editor area will put cursor to top and pop up keyboard. But on Android, click lower part of editor area will not pop up keyboard, user can only press first line of editor to start input.

Any update on this?

**Comment by SRSMurthy** [comment]
> Any update about fixing thit issue

Wrap editing area with <Pressable>
