### ISSUE TITLE
IOS status bar turns white when editor is in focus

### ISSUE THREAD

**Issue by arstropica** [wxik/react-native-rich-editor#68]
First, thanks for supporting a great tool.  
As the title states, the IOS status bar style is changing to white once the editor is in focus (and stays white until the app closes).  I've tried using just default options to see if this is something related to the plugin configuration but the bug appears with default settings.
This could be related to an existing react native webview bug documented [here](https://github.com/react-native-community/react-native-webview/issues/735). 
My current fix is to (re)set the status bar style in the component itself, but this is not ideal.  Any help / suggestions would be appreciated. Thanks!

**Comment by bhaskardabhi** [comment]
@arstropica were you able to resolve the issue? I am still facing same issue.

**Comment by stulip** [comment]
I took a look at the RN webview related issues, and it said [here,](https://github.com/react-native-webview/react-native-webview/issues/735#issuecomment-570935900) it should be after the keyboard pops up according to the system Changed the status bar

**Comment by arstropica** [comment]
Here is what I ended up doing.  It's ugly but it worked...

`import {
  StatusBar,
  Appearance,
  Platform,
} from 'react-native';

class Example extends Component {

 constructor(props) {
    super(props);
    const colorScheme =
      Platform.OS === 'ios' ? Appearance.getColorScheme() : null;
    this.state = {
      isIOS: Platform.OS === 'ios',
      barStyle: colorScheme
        ? (colorScheme === 'dark' ? 'light' : 'dark') + '-content'
        : null,
    };
  }

  componentDidUpdate(prevProps, prevState) {
    if (prevState.isIOS) {
      this.fixStatusBar();
    }
  }

  fixStatusBar = () => {
    const { barStyle, isIOS } = this.state;
    if (isIOS && barStyle !== StatusBar.barStyle) {
      StatusBar.setBarStyle(barStyle);
    }
  };
}
`
