### ISSUE TITLE
Scrolling is not working 

### ISSUE THREAD

**Issue by harleenarora** [wxik/react-native-rich-editor#71]
Hi, I am using "react-native-pell-rich-editor": "^1.3.0". Please tell how to solved this problem?

**Comment by marlti7** [comment]
same porblem

**Comment by AkalUstat** [comment]
i wrapped my editor in a scrollview and was able to get it to scroll

**Comment by cmcaboy** [comment]
@AkalUstat Were you able to get it working on Android?

**Comment by adyra** [comment]
I successfully manage to make editor scrollable in android. You need to wrap editor component in scrollView, set the height of scrollView, and the important props that it make work in android is set props nestedScrollEnabled to true.

`<ScrollView
  nestedScrollEnabled={true}
  style={{flex: 1, height: 400}}>
  <RichEditor
    ref={this.richText}
    initialContentHTML={this.state.htmlContent}
  />
</ScrollView>`

**Comment by jessypouliot98** [comment]
Unfortunately, this fix only works if your RichTextEditor has disabled={false}. When disable, this doesn't work anymore

**Comment by jessypouliot98** [comment]
> Unfortunately, this fix only works if your RichTextEditor has disabled={false}. When disable, this doesn't work anymore

I found a fix for that:

```
state = {
    disabled: false,
};

// --

<ScrollView>
    <RichTextEditor
        disabled={this.state.disabled}
        scrollEnabled={false}
        editorInitializedCallback={() => this.setState({ disabled: true })}
    />
</ScrollView>
```

On Android, if the editor is disabled, it is not fully rendered somehow, with this hack you can get it to render and disable it on render

**Comment by stulip** [comment]
version: 1.8.2
