### ISSUE TITLE
Toggle modes

### ISSUE THREAD

**Issue by alanludin** [wxik/react-native-rich-editor#76]
Hi! I'm having trouble when cycling through editor modes, they start to stick to each other (bold and italic turn on and off at the same time), and i can't turn an individual mode off by tapping on it again. Is this an issue? Is there a specific method to turn off a mode?

Thanks in advance.

**Comment by chungmktg** [comment]
in file editor.js of library at 266 line, delete line "flag && focusCurrent();" will see magic.

  var message = function (event){
                var msgData = JSON.parse(event.data), action = Actions[msgData.type];
                if (action ){
                    if ( action[msgData.name]){
                        var flag = msgData.name === 'result';
                        //flag && focusCurrent(); <----- -------------------------------remove this line-------------------------------------->
                        action[msgData.name](msgData.data);
                        flag && handler();
                    } else {
                        action(msgData.data);
                    }
                }
            };

**Comment by stulip** [comment]
``` flag && focusCurrent(); ```
The problem is the keyboard. Let me confirm again if it can be removed.
