### ISSUE TITLE
Module is not a registered callable module(calling onMessage

### ISSUE THREAD

**Issue by Anzormumladze** [wxik/react-native-rich-editor#77]
Bug description:

On Android I have the bug invariant violation: Module is not a registered callable module (calling onMessage)

To Reproduce:

Expected behavior:

Screenshots/Videos:
![image](https://user-images.githubusercontent.com/46164149/94109980-e8849d80-fe52-11ea-87c1-29425d194470.png)

Environment:

OS: Android
OS version:
"react-native": "0.60.6",

Conclusion: 
it's react-native-webview problem,your package is out of date ,please upgrade

**Comment by onurcskun** [comment]
any solution ?

**Comment by Anzormumladze** [comment]
@onurcskun in my case,solution was to delete react native webview package and unlink it .then installed again

**Comment by jf-ouellette** [comment]
@onurcskun It seems to be related to react-native-webview version: https://github.com/react-native-webview/react-native-webview/issues/1324. The solution proposed in the thread is to downgrade react-native-webview to 9.0.2 which seems to solve the problem for me too, but is not ideal.

**Comment by onurcskun** [comment]
@Anzormumladze and @jf-ouellette thank you both, it helped but as you said it is not ideal ..
