### ISSUE TITLE
Can not access reference

### ISSUE THREAD

**Issue by Florian-Bolli** [wxik/react-native-rich-editor#80]
Hi, first thank you for this module! :)

I wanted to implement a custom function to make colored text, but I have a prblem accessing the richText reference.

 In render()
```
<RichEditor
    ref={(ref) => this.richText = ref}
    initialContentHTML={'Hello <b>World</b> <p style="color: red">this is a new paragraph</p> <p>this is another new paragraph</p>'}
    onEditorInitialized={() => this.editorInitializedCallback()}
    onChange = {(event)=>console.log(event)}
/>
```

and my custom action, motivated from your example.js:
```
handleCustomAction(){
    console.log("handleCustomAction");
    this.richText.current?.setContentHTML("HELLO WORLD");
}
```

If I call the custom action from the RichToolbar, there is an error: 
this.richtext.current seems to be undefined.

Can you help me?
Thx.

**Comment by tomgiam** [comment]
Try using: 

  richText = React.createRef();

before the constructor like this:

class HTMLEditor extends Component {
  richText = React.createRef();
  constructor(props) {

I also use this:

              ref={this.richText}

instead of:

ref={(ref) => this.richText = ref}

**Comment by tringbhagya** [comment]
@Florian-Bolli I too faced the same issue while loading this component in FlatList. After spending lot of hours finally found the reason. While mapping the custom action, "**this**" itself holds the reference of toolbar which is supposed to be our component reference. Change the custom action function to arrow function or calling the action inside arrow function will solve this issue. 

Try anyone of below approaches.
`handleCustomAction = () => { }`
or
'actionName' = {() => {this.handleCustomAction() }}`

**Comment by Florian-Bolli** [comment]
Thank you guys for replying even if my question was formated very badly... was actually my first github comment 

@tringbhagya  Yesss, thank you!
@tomgiam I think this has just something to do with the RN version
