### ISSUE TITLE
Are there any plans to support markdown?

### ISSUE THREAD

**Issue by polcats** [wxik/react-native-rich-editor#86]

**Comment by socialcode-rob1** [comment]
@polcats I'm interested in something similar, just not there yet.

Have you explored using any third-party processors?
i.e. https://domchristie.github.io/turndown/

**Comment by polcats** [comment]
Yep, we ended up using turndown :) It's a great solution.
I will also be closing this issue. Thanks!

**Comment by oguzydz** [comment]
any update, https://domchristie.github.io/turndown/  this is not existing.
