### ISSUE TITLE
focusContentEditor() is not showing keyboard when called after a Modal is closed

### ISSUE THREAD

**Issue by polcats** [wxik/react-native-rich-editor#90]
I have a component that pops out as a modal to get user input (link name and URL).
Once it closes, I want to focus on the editor again by calling focusContentEditor().

But what happens is that:
1. The editor gets focused; But
2. The keyboard is not showing up

My modal is something like this:
`LinkPrompt.tsx`
```
    <Modal
      onBackdropPress={cancelAddLink}
      isVisible={visible}
    > ...
```

the cancelAddLink is something like
`RichTextExtended.tsx`
```
  const [addLink, setAddLink] = useState(false);

  const cancelAddLink = () => {
    setAddLink(false);
    richTextRef?.focusContentEditor();
  };
```

**Comment by stulip** [comment]
Please provide the relevant system and version information, my test is normal

**Comment by polcats** [comment]
Some relevant version details:
- react 16.13.1.
- react-native 0.63.2
- react-native-pell-rich-editor 1.3.0.

Other functions like `insertLink` and `blurContentEditor` are working fine.

@stulip Could you also share the setup that you used for testing? Thanks!

**Comment by polcats** [comment]
I finally found the workaround for this, adding a slight delay worked.
```
  const cancelAddLink = () => {
    setAddLink(false);
    setTimeout(() => {
      richTextRef.current?.focusContentEditor();
    }, 200);
  };
```
I will be closing this issue now. Thanks!

**Comment by stulip** [comment]
If the test result is not applicable to `modal`, the keyboard will not disappear automatically after insertLink, even if `focusContentEditor` is not applicable

Refer to the examples project
