### ISSUE TITLE
Link is not clickable

### ISSUE THREAD

**Issue by jte0711** [wxik/react-native-rich-editor#98]
Hi, I can't click the link made from `insertLink` and `insertHTML`, it seems that they add `\` after `href=`. Here is an example of my `insertLink` result:

`<a href=\"www.google.com\"></a>`

**Comment by karpov-denys** [comment]
I have similar problem. In my case I use RichEditor as view for html. I click on link, but nothing happens. 
```
....
<RichEditor
      disabled={true}
      useContainer={true}
      initialContentHTML={textContent}
      onHeightChange={(height: number) => {
        setEditorHeight(height);
      }}
      editorStyle={{
        contentCSSText: `padding: 0px; margin: 0px;${contentCSSStyles}`,
        cssText: `*{ margin: 0; padding: 0;} li{margin-left: 35px} ${cssStyles}`,
      }}
    />
....
```

**Comment by stulip** [comment]
need http:\\www.google.com or https:\\www.google.com
