### ISSUE TITLE
bug using pasteAsPlainText

### ISSUE THREAD

**Issue by ascott** [wxik/react-native-rich-editor#99]
i'm using the editor like this
```
<RichEditor
  ref={richText}
  placeholder={placeholder}
  initialContentHTML={content}
  onChange={onChange}
  editorStyle={styles.editorStyle}
  pasteAsPlainText={true}
/>
```

and still html pasting occurs.

i'm using:
```
"react": "16.13.1",
"react-native": "0.63.3",
```

![Screen-Recording-2020-11-07-at-3](https://user-images.githubusercontent.com/130878/98453633-470a9000-2110-11eb-8f36-891f68d8e824.gif)

**Comment by ascott** [comment]
looks like possibly this feature has not been released as an npm release yet... i forked the repo and installed from there and the `pasteAsPlainText` functionality is working. 👍

**Comment by apgsn** [comment]
No need to fork, just execute `npm install https://github.com/wxik/react-native-rich-editor` and you're set.

**Comment by stulip** [comment]
1.4.0
